# Generated by Django 3.0.6 on 2020-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekart', '0002_auto_20200517_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desciption',
            new_name='product_big_desciption',
        ),
        migrations.AddField(
            model_name='product',
            name='product_small_desciption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
