# Generated by Django 3.0.6 on 2020-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekart', '0003_auto_20200517_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=100)),
                ('product_small_desciption', models.TextField()),
                ('product_big_desciption', models.TextField()),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=100)),
                ('product_small_desciption', models.TextField()),
                ('product_big_desciption', models.TextField()),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Camera',
        ),
    ]
