# Generated by Django 3.0.6 on 2020-05-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekart', '0004_auto_20200517_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='product_big_desciption',
            new_name='product_big_description',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='product_small_desciption',
            new_name='product_small_description',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='product_big_desciption',
            new_name='product_big_description',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='product_small_desciption',
            new_name='product_small_description',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='product_big_desciption',
            new_name='product_big_description',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='product_small_desciption',
            new_name='product_small_description',
        ),
    ]
