# Generated by Django 3.0.6 on 2020-05-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekart', '0005_auto_20200517_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='company_name',
            field=models.CharField(default='fkart', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='company_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobile',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
